# Generated by Django 6.1.1 on 2026-10-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_release_data_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
    ]
